"""Generate all FDTD data files from scratch.

Produces sigma_bond.py, sigma_ring.py, sigma_nnn.py, kappa_table.py at L=100.
Convergence verified: L=100 vs L=120 within 3.2% (tests/convergence_scan.py).

Run: cd tests/data && OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 /usr/bin/python3 generate_all.py
Expected time: ~75 min (M3 MacBook Air).

Parameters: L=100, DW=15, DT=0.25, sx=8.0, r_m=20, K1=1.0, K2=0.5.

NOTE: sigma_bond at L=80 showed ~12% systematic bias across ALL k
(not only at k=0.3 as for sigma_ring). Two separate effects:
  1. PML contamination at low k (affects ring 44-51% at k=0.3)
  2. Uniform ~12% bias for single-bond scatterer (cause: near-field or
     box-size effect for small scatterer)
Both converge away at L=100 (max Δ vs L=120: bond 1.4%, ring R=9 3.2%).
See tests/convergence_scan.py for full data.
"""
import sys
import os
import numpy as np
import time

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', 'src'))

from elastic_3d import scalar_laplacian_3d, make_damping_3d, run_fdtd_3d
from gauge_3d import make_vortex_force
from scattering_3d import (make_wave_packet_3d, make_sphere_points,
                           compute_sphere_f2, integrate_sigma_3d,
                           estimate_n_steps_3d)

# ── Parameters ────────────────────────────────────────────────────
K1, K2 = 1.0, 0.5
L = 100
DW = 15
DS = 1.5
DT = 0.25
sx = 8.0
r_m = 20
THETAS = np.linspace(0, np.pi, 13)
PHIS = np.linspace(0, 2 * np.pi, 24, endpoint=False)

k_vals = np.array([0.3, 0.5, 0.7, 0.9, 1.1, 1.3, 1.5])

CENTER = L // 2
X_START = CENTER - 20

HEADER = f'''"""Generated by data/generate_all.py
Parameters: L={L}, DW={DW}, DT={DT}, sx={sx}, r_m={r_m}, K1={K1}, K2={K2}
"""
import numpy as np
'''


# ── Shared infrastructure ────────────────────────────────────────

def setup_fdtd():
    """Create shared FDTD objects."""
    gamma_pml = make_damping_3d(L, DW, DS)
    iz, iy, ix = make_sphere_points(L, r_m, THETAS, PHIS)
    return gamma_pml, iz, iy, ix


def force_plain(ux, uy, uz):
    return scalar_laplacian_3d(ux, uy, uz, K1, K2)


def compute_references(gamma_pml, iz, iy, ix):
    """Run reference (no defect) FDTD at all k values. Shared across datasets."""
    refs = {}
    for k0 in k_vals:
        ux0, vx0 = make_wave_packet_3d(L, k0, X_START, sx, K1, K2)
        ns = estimate_n_steps_3d(k0, L, X_START, sx, r_m, DT, 50, K1, K2)
        ref = run_fdtd_3d(force_plain, ux0.copy(), vx0.copy(), gamma_pml,
                          DT, ns, rec_iz=iz, rec_iy=iy, rec_ix=ix, rec_n=ns)
        refs[k0] = (ref, ux0, vx0, ns)
        print(f"    ref k={k0:.1f}: ns={ns}", flush=True)
    return refs


def run_sigma_tr(force_fn, refs, gamma_pml, iz, iy, ix):
    """Run defect FDTD and return sigma_tr array."""
    sigma_tr = np.zeros(len(k_vals))
    for i, k0 in enumerate(k_vals):
        ref, ux0, vx0, ns = refs[k0]
        d = run_fdtd_3d(force_fn, ux0.copy(), vx0.copy(), gamma_pml,
                        DT, ns, rec_iz=iz, rec_iy=iy, rec_ix=ix, rec_n=ns)
        f2 = compute_sphere_f2(d['ux'], d['uy'], d['uz'],
                               ref['ux'], ref['uy'], ref['uz'], r_m)
        _, st = integrate_sigma_3d(f2, THETAS, PHIS)
        sigma_tr[i] = st
        print(f"      k={k0:.1f}: σ_tr = {st:.3f}", flush=True)
    return sigma_tr


def run_sigma_tr_and_pol(force_fn, refs, gamma_pml, iz, iy, ix):
    """Single FDTD run → sigma_tr, sigma_xx, sigma_xy from same data."""
    sigma_tr = np.zeros(len(k_vals))
    sigma_xx = np.zeros(len(k_vals))
    sigma_xy = np.zeros(len(k_vals))
    for i, k0 in enumerate(k_vals):
        ref, ux0, vx0, ns = refs[k0]
        d = run_fdtd_3d(force_fn, ux0.copy(), vx0.copy(), gamma_pml,
                        DT, ns, rec_iz=iz, rec_iy=iy, rec_ix=ix, rec_n=ns)
        # Total f2
        f2 = compute_sphere_f2(d['ux'], d['uy'], d['uz'],
                               ref['ux'], ref['uy'], ref['uz'], r_m)
        _, st = integrate_sigma_3d(f2, THETAS, PHIS)
        sigma_tr[i] = st
        # Per-polarization f2 from same FDTD run (same inc2 as compute_sphere_f2)
        sc_ux = d['ux'] - ref['ux']
        sc_uy = d['uy'] - ref['uy']
        sc_uz = d['uz'] - ref['uz']
        inc2 = np.mean(ref['ux']**2 + ref['uy']**2 + ref['uz']**2, axis=0)
        inc2_floor = max(1e-30, 1e-12 * np.max(inc2))
        inc2 = np.maximum(inc2, inc2_floor)
        f2_xx = r_m**2 * np.mean(sc_ux**2, axis=0) / inc2
        f2_xy = r_m**2 * np.mean(sc_uy**2, axis=0) / inc2
        f2_xz = r_m**2 * np.mean(sc_uz**2, axis=0) / inc2
        _, st_xx = integrate_sigma_3d(f2_xx, THETAS, PHIS)
        _, st_xy = integrate_sigma_3d(f2_xy, THETAS, PHIS)
        _, st_xz = integrate_sigma_3d(f2_xz, THETAS, PHIS)
        sigma_xx[i] = st_xx
        sigma_xy[i] = st_xy
        # Verify: σ_xx + σ_xy + σ_xz = σ_tr (same FDTD run, same normalization)
        assert abs(st_xx + st_xy + st_xz - st) / st < 0.01, \
            f"k={k0}: polarization sum {st_xx+st_xy+st_xz:.4f} ≠ σ_tr {st:.4f}"
        print(f"      k={k0:.1f}: σ_tr={st:.3f}, σ_xx={st_xx:.4f}, σ_xy={st_xy:.4f}, σ_xz={st_xz:.6f}",
              flush=True)
    return sigma_tr, sigma_xx, sigma_xy


def fmt_array(arr, decimals=3):
    """Format numpy array values as comma-separated string."""
    return ", ".join(f"{v:.{decimals}f}" for v in arr)


# ── File writers ─────────────────────────────────────────────────

def write_sigma_bond(sigma_bond, sigma_xx, sigma_xy):
    """Write sigma_bond.py."""
    lines = [HEADER]
    lines.append(f"k_vals = np.array([{fmt_array(k_vals)}])")
    lines.append("")
    lines.append("# Total per-bond sigma_tr")
    lines.append(f"sigma_bond = np.array([{fmt_array(sigma_bond, 4)}])")
    lines.append("")
    lines.append("# Polarization-resolved (alpha=0.30)")
    lines.append(f"sigma_xx = np.array([{fmt_array(sigma_xx, 4)}])")
    lines.append(f"sigma_xy = np.array([{fmt_array(sigma_xy, 4)}])")
    lines.append("")
    lines.append("# ── Self-consistency ─────────────────────────────────────────────")
    lines.append("# sigma_xx + sigma_xy ≈ sigma_bond (sigma_xz = 0: single z-bond, uz decoupled)")
    lines.append('assert all(np.abs(sigma_xx + sigma_xy - sigma_bond) < 0.001), \\')
    lines.append('    "sigma_xx + sigma_xy ≠ sigma_bond beyond rounding"')
    lines.append("assert len(sigma_bond) == len(k_vals) == 7")
    lines.append('assert all(sigma_bond > 0), "sigma_bond must be positive"')
    lines.append('assert np.mean(sigma_xx) > np.mean(sigma_xy), \\')
    lines.append('    "sigma_xx should dominate sigma_xy on average"')
    lines.append("")

    path = os.path.join(os.path.dirname(__file__), "sigma_bond.py")
    with open(path, "w") as f:
        f.write("\n".join(lines))
    print(f"  Written: {path}", flush=True)


def write_sigma_ring(sigma_ring, sigma_alpha_nn):
    """Write sigma_ring.py. Uses only existing keys (safe for checkpoints)."""
    R_keys = sorted(sigma_ring.keys())
    a_keys = sorted(sigma_alpha_nn.keys())

    lines = [HEADER]
    lines.append(f"k_vals = np.array([{fmt_array(k_vals)}])")
    lines.append("")
    lines.append("# sigma_tr(k) at alpha=0.30, NN gauging, various R")
    lines.append("sigma_ring = {")
    for R in R_keys:
        lines.append(f"    {R}: np.array([{fmt_array(sigma_ring[R])}]),")
    lines.append("}")
    lines.append("")
    lines.append("# sigma_tr(k) at various alpha, R=5, NN gauging")
    lines.append("sigma_alpha_nn = {")
    for a in a_keys:
        lines.append(f"    {a:.2f}: np.array([{fmt_array(sigma_alpha_nn[a])}]),")
    lines.append("}")
    lines.append("")
    lines.append("# ── Self-consistency ─────────────────────────────────────────────")
    # Only add cross-checks if data is complete
    if 5 in sigma_ring and 0.30 in sigma_alpha_nn:
        lines.append("np.testing.assert_array_equal(sigma_ring[5], sigma_alpha_nn[0.30],")
        lines.append('                              err_msg="sigma_ring[5] ≠ sigma_alpha_nn[0.30]")')
    if len(R_keys) >= 4:
        lines.append("# sigma grows with R at fixed k")
        lines.append("for _ik in range(7):")
        lines.append("    for _R1, _R2 in [(3, 5), (5, 7), (7, 9)]:")
        lines.append("        assert sigma_ring[_R2][_ik] > sigma_ring[_R1][_ik], \\")
        lines.append('            f"sigma not monotonic in R at k index {_ik}: R={_R1}→{_R2}"')
    if len(a_keys) >= 2:
        alpha_pairs = [(a_keys[i], a_keys[i+1]) for i in range(len(a_keys)-1)]
        lines.append("# sigma grows with alpha at fixed k")
        lines.append("for _ik in range(7):")
        lines.append(f"    for _a1, _a2 in {alpha_pairs}:")
        lines.append("        assert sigma_alpha_nn[_a2][_ik] > sigma_alpha_nn[_a1][_ik], \\")
        lines.append('            f"sigma not monotonic in alpha at k index {_ik}: α={_a1}→{_a2}"')
    lines.append("")

    path = os.path.join(os.path.dirname(__file__), "sigma_ring.py")
    with open(path, "w") as f:
        f.write("\n".join(lines))
    print(f"  Written: {path}", flush=True)


def write_sigma_nnn(sigma_nnn):
    """Write sigma_nnn.py."""
    lines = [HEADER]
    lines.append(f"k_vals = np.array([{fmt_array(k_vals)}])")
    lines.append("")
    lines.append("# sigma_tr(k) at various alpha, R=5, NNN gauging")
    lines.append("sigma_nnn = {")
    for a in sorted(sigma_nnn.keys()):
        lines.append(f"    {a:.2f}: np.array([{fmt_array(sigma_nnn[a])}]),")
    lines.append("}")
    lines.append("")
    lines.append("# ── Self-consistency ─────────────────────────────────────────────")
    lines.append("# sigma_nnn grows with alpha at fixed k")
    lines.append("for _ik in range(7):")
    lines.append("    for _a1, _a2 in [(0.10, 0.15), (0.15, 0.20), (0.20, 0.25), (0.25, 0.30)]:")
    lines.append("        assert sigma_nnn[_a2][_ik] > sigma_nnn[_a1][_ik], \\")
    lines.append('            f"sigma_nnn not monotonic in alpha at k index {_ik}: α={_a1}→{_a2}"')
    lines.append("")

    path = os.path.join(os.path.dirname(__file__), "sigma_nnn.py")
    with open(path, "w") as f:
        f.write("\n".join(lines))
    print(f"  Written: {path}", flush=True)


def write_kappa_table(kappa_nn, kappa_nnn):
    """Write kappa_table.py."""
    lines = [HEADER]
    lines.append("# kappa_NN(alpha) at k-cutoffs (from sigma_alpha_nn, R=5)")
    lines.append("kappa_nn = {")
    lines.append("    # alpha: (k<=0.9, k<=1.5)")
    for a in sorted(kappa_nn.keys()):
        lines.append(f"    {a:.2f}: ({fmt_array(kappa_nn[a])}),")
    lines.append("}")
    lines.append("")
    lines.append("# kappa_NNN(alpha) at k-cutoffs (from sigma_nnn, R=5)")
    lines.append("kappa_nnn = {")
    lines.append("    # alpha: (k<=0.9, k<=1.5)")
    for a in sorted(kappa_nnn.keys()):
        lines.append(f"    {a:.2f}: ({fmt_array(kappa_nnn[a])}),")
    lines.append("}")
    lines.append("")
    lines.append("# ── Self-consistency ─────────────────────────────────────────────")
    lines.append(f"_alphas_nn = {sorted(kappa_nn.keys())}")
    lines.append("# kappa_nn monotonic in alpha (k<=0.9 column)")
    lines.append("for _i in range(len(_alphas_nn) - 1):")
    lines.append("    assert kappa_nn[_alphas_nn[_i + 1]][0] > kappa_nn[_alphas_nn[_i]][0], \\")
    lines.append('        f"kappa_nn not monotonic: α={_alphas_nn[_i]}→{_alphas_nn[_i+1]}"')
    lines.append("# kappa_nnn > kappa_nn at matching alpha")
    lines.append("for _a in [0.10, 0.15, 0.20, 0.25, 0.30]:")
    lines.append("    assert kappa_nnn[_a][0] > kappa_nn[_a][0], \\")
    lines.append('        f"kappa_nnn ≤ kappa_nn at α={_a} (k≤0.9)"')
    lines.append("# kappa grows with k-cutoff (more spectrum = more drag)")
    lines.append("for _a in kappa_nn:")
    lines.append("    assert kappa_nn[_a][1] > kappa_nn[_a][0], \\")
    lines.append('        f"kappa_nn(k≤1.5) ≤ kappa_nn(k≤0.9) at α={_a}"')
    lines.append("for _a in kappa_nnn:")
    lines.append("    assert kappa_nnn[_a][1] > kappa_nnn[_a][0], \\")
    lines.append('        f"kappa_nnn(k≤1.5) ≤ kappa_nnn(k≤0.9) at α={_a}"')
    lines.append("")

    path = os.path.join(os.path.dirname(__file__), "kappa_table.py")
    with open(path, "w") as f:
        f.write("\n".join(lines))
    print(f"  Written: {path}", flush=True)


# ── Generators ────────────────────────────────────────────────────

def generate_sigma_bond(refs, gamma_pml, iz, iy, ix):
    """Single FDTD run → sigma_bond + polarization decomposition."""
    print("\n>>> sigma_bond (single z-bond, α=0.30)", flush=True)
    f_def = make_vortex_force(0.30, 0, L, K1, K2)
    # Verify R_loop=0 gives exactly 1 gauged bond (need gradient field, not const)
    u_test = np.zeros((L, L, L))
    for iz_t in range(L):
        u_test[iz_t, :, :] = iz_t * 0.01  # gradient in z → Δu ≠ 0 on z-bonds
    z_test = np.zeros((L, L, L))
    fx, _, _ = f_def(u_test, z_test, z_test)
    fx_plain, _, _ = force_plain(u_test, z_test, z_test)
    diff = np.max(np.abs(fx - fx_plain))
    n_gauged = np.sum(np.abs(fx - fx_plain) > 1e-6)
    assert diff > 1e-4, f"R_loop=0 gives no gauged bonds (diff={diff:.2e})"
    assert n_gauged == 2, f"R_loop=0 gave {n_gauged} gauged sites (expected 2: one bond, two sites)"
    print(f"  R_loop=0 verified: {n_gauged} sites = {n_gauged//2} bond(s), diff={diff:.4f}", flush=True)
    sigma_bond, sigma_xx, sigma_xy = run_sigma_tr_and_pol(
        f_def, refs, gamma_pml, iz, iy, ix)
    write_sigma_bond(sigma_bond, sigma_xx, sigma_xy)
    return sigma_bond


def generate_sigma_ring(refs, gamma_pml, iz, iy, ix):
    """R-scan + α-scan, NN gauging. Writes checkpoint after each dataset."""
    R_values = [3, 5, 7, 9]
    alpha_values = [0.10, 0.15, 0.20, 0.25, 0.30, 0.40, 0.50]

    # R scan at α=0.30
    sigma_ring = {}
    sigma_alpha_nn = {}
    for R in R_values:
        print(f"\n>>> sigma_ring R={R} (α=0.30)", flush=True)
        f_def = make_vortex_force(0.30, R, L, K1, K2)
        sigma_ring[R] = run_sigma_tr(f_def, refs, gamma_pml, iz, iy, ix)
        # Checkpoint after each R
        write_sigma_ring(sigma_ring, sigma_alpha_nn)

    # α scan at R=5
    for a in alpha_values:
        if a == 0.30:
            sigma_alpha_nn[a] = sigma_ring[5].copy()
            print(f"\n>>> sigma_alpha α={a} R=5: reused from sigma_ring[5]", flush=True)
        else:
            print(f"\n>>> sigma_alpha α={a} R=5", flush=True)
            f_def = make_vortex_force(a, 5, L, K1, K2)
            sigma_alpha_nn[a] = run_sigma_tr(f_def, refs, gamma_pml, iz, iy, ix)
        # Checkpoint: write after each dataset completes
        write_sigma_ring(sigma_ring, sigma_alpha_nn)

    return sigma_ring, sigma_alpha_nn


def generate_sigma_nnn(refs, gamma_pml, iz, iy, ix):
    """NNN gauging at multiple α. Writes checkpoint after each α."""
    alpha_values_nnn = [0.10, 0.15, 0.20, 0.25, 0.30]
    sigma_nnn = {}
    for a in alpha_values_nnn:
        print(f"\n>>> sigma_nnn α={a:.2f} (R=5, NNN gauging)", flush=True)
        f_def = make_vortex_force(a, 5, L, K1, K2, gauge_nnn=True)
        sigma_nnn[a] = run_sigma_tr(f_def, refs, gamma_pml, iz, iy, ix)
        # Checkpoint: write after each alpha completes
        write_sigma_nnn(sigma_nnn)
    return sigma_nnn


def generate_kappa_table(sigma_alpha_nn, sigma_nnn):
    """Compute kappa from sigma data (post-processing, no FDTD)."""
    print("\n>>> kappa_table (post-processing)", flush=True)
    N_POL = 2
    R = 5
    K_CUTOFFS = [0.9, 1.5]

    def compute_kappa(sigma_arr, R_loop, cutoffs):
        prefactor = N_POL * R_loop / (4 * np.pi**2)
        integrand = np.sin(k_vals)**2 * sigma_arr
        kappas = []
        for kc in cutoffs:
            mask = k_vals <= kc + 0.01
            # trapz on uniform Δk=0.2 grid: error O(Δk²) ≈ 4%
        kappas.append(prefactor * np.trapz(integrand[mask], k_vals[mask]))
        return tuple(kappas)

    kappa_nn = {}
    for a in sorted(sigma_alpha_nn.keys()):
        kappa_nn[a] = compute_kappa(sigma_alpha_nn[a], R, K_CUTOFFS)
        print(f"  κ_NN(α={a:.2f}): k≤0.9={kappa_nn[a][0]:.3f}, k≤1.5={kappa_nn[a][1]:.3f}",
              flush=True)

    kappa_nnn = {}
    for a in sorted(sigma_nnn.keys()):
        kappa_nnn[a] = compute_kappa(sigma_nnn[a], R, K_CUTOFFS)
        print(f"  κ_NNN(α={a:.2f}): k≤0.9={kappa_nnn[a][0]:.3f}, k≤1.5={kappa_nnn[a][1]:.3f}",
              flush=True)

    write_kappa_table(kappa_nn, kappa_nnn)


# ── Main ─────────────────────────────────────────────────────────

if __name__ == "__main__":
    t_total = time.time()
    print(f"generate_all.py: L={L}, {len(k_vals)} k-pts")
    print(f"Parameters: DW={DW}, DT={DT}, sx={sx}, r_m={r_m}, K1={K1}, K2={K2}")

    gamma_pml, iz, iy, ix = setup_fdtd()

    print("\n>>> Computing references (shared across all datasets)...", flush=True)
    refs = compute_references(gamma_pml, iz, iy, ix)

    # 1. sigma_bond (single z-bond + polarization, single FDTD run)
    sigma_bond = generate_sigma_bond(refs, gamma_pml, iz, iy, ix)

    # 2. sigma_ring (R-scan + α-scan, with checkpoints)
    sigma_ring, sigma_alpha_nn = generate_sigma_ring(refs, gamma_pml, iz, iy, ix)

    # 3. sigma_nnn (NNN gauging, multiple α, with checkpoints)
    sigma_nnn = generate_sigma_nnn(refs, gamma_pml, iz, iy, ix)

    # 4. kappa_table (post-processing from sigma, no FDTD)
    generate_kappa_table(sigma_alpha_nn, sigma_nnn)

    dt = (time.time() - t_total) / 60
    print(f"\n\nTotal time: {dt:.1f} min")
    print("Done. All data files regenerated.")
