"""Generated by data/generate_all.py
Parameters: L=100, DW=15, DT=0.25, sx=8.0, r_m=20, K1=1.0, K2=0.5
"""
import numpy as np

# kappa_NN(alpha) at k-cutoffs (from sigma_alpha_nn, R=5)
kappa_nn = {
    # alpha: (k<=0.9, k<=1.5)
    0.10: (0.022, 0.049),
    0.15: (0.071, 0.145),
    0.20: (0.162, 0.315),
    0.25: (0.287, 0.557),
    0.30: (0.428, 0.844),
    0.40: (0.674, 1.386),
    0.50: (0.769, 1.614),
}

# kappa_NNN(alpha) at k-cutoffs (from sigma_nnn, R=5)
kappa_nnn = {
    # alpha: (k<=0.9, k<=1.5)
    0.10: (0.087, 0.238),
    0.15: (0.209, 0.556),
    0.20: (0.393, 1.016),
    0.25: (0.628, 1.593),
    0.30: (0.889, 2.227),
}

# ── Self-consistency ─────────────────────────────────────────────
_alphas_nn = [0.1, 0.15, 0.2, 0.25, 0.3, 0.4, 0.5]
# kappa_nn monotonic in alpha (k<=0.9 column)
for _i in range(len(_alphas_nn) - 1):
    assert kappa_nn[_alphas_nn[_i + 1]][0] > kappa_nn[_alphas_nn[_i]][0], \
        f"kappa_nn not monotonic: α={_alphas_nn[_i]}→{_alphas_nn[_i+1]}"
# kappa_nnn > kappa_nn at matching alpha
for _a in [0.10, 0.15, 0.20, 0.25, 0.30]:
    assert kappa_nnn[_a][0] > kappa_nn[_a][0], \
        f"kappa_nnn ≤ kappa_nn at α={_a} (k≤0.9)"
# kappa grows with k-cutoff (more spectrum = more drag)
for _a in kappa_nn:
    assert kappa_nn[_a][1] > kappa_nn[_a][0], \
        f"kappa_nn(k≤1.5) ≤ kappa_nn(k≤0.9) at α={_a}"
for _a in kappa_nnn:
    assert kappa_nnn[_a][1] > kappa_nnn[_a][0], \
        f"kappa_nnn(k≤1.5) ≤ kappa_nnn(k≤0.9) at α={_a}"
