"""Generated by data/generate_all.py
Parameters: L=100, DW=15, DT=0.25, sx=8.0, r_m=20, K1=1.0, K2=0.5
"""
import numpy as np

k_vals = np.array([0.300, 0.500, 0.700, 0.900, 1.100, 1.300, 1.500])

# sigma_tr(k) at alpha=0.30, NN gauging, various R
sigma_ring = {
    3: np.array([9.802, 5.505, 3.116, 2.063, 1.571, 1.313, 1.261]),
    5: np.array([28.331, 12.311, 7.090, 4.688, 3.495, 2.912, 2.601]),
    7: np.array([48.537, 19.592, 11.212, 7.569, 5.805, 4.872, 4.360]),
    9: np.array([78.060, 31.301, 18.018, 12.377, 9.561, 7.973, 7.215]),
}

# sigma_tr(k) at various alpha, R=5, NN gauging
sigma_alpha_nn = {
    0.10: np.array([1.672, 0.577, 0.342, 0.253, 0.216, 0.210, 0.212]),
    0.15: np.array([5.958, 2.020, 1.093, 0.743, 0.592, 0.541, 0.524]),
    0.20: np.array([12.830, 4.690, 2.518, 1.650, 1.258, 1.098, 1.025]),
    0.25: np.array([20.790, 8.333, 4.605, 3.005, 2.247, 1.904, 1.729]),
    0.30: np.array([28.331, 12.311, 7.090, 4.688, 3.495, 2.912, 2.601]),
    0.40: np.array([39.055, 18.800, 11.612, 7.987, 6.039, 4.986, 4.396]),
    0.50: np.array([42.656, 21.181, 13.417, 9.395, 7.171, 5.926, 5.215]),
}

# ── Self-consistency ─────────────────────────────────────────────
np.testing.assert_array_equal(sigma_ring[5], sigma_alpha_nn[0.30],
                              err_msg="sigma_ring[5] ≠ sigma_alpha_nn[0.30]")
# sigma grows with R at fixed k
for _ik in range(7):
    for _R1, _R2 in [(3, 5), (5, 7), (7, 9)]:
        assert sigma_ring[_R2][_ik] > sigma_ring[_R1][_ik], \
            f"sigma not monotonic in R at k index {_ik}: R={_R1}→{_R2}"
# sigma grows with alpha at fixed k
for _ik in range(7):
    for _a1, _a2 in [(0.1, 0.15), (0.15, 0.2), (0.2, 0.25), (0.25, 0.3), (0.3, 0.4), (0.4, 0.5)]:
        assert sigma_alpha_nn[_a2][_ik] > sigma_alpha_nn[_a1][_ik], \
            f"sigma not monotonic in alpha at k index {_ik}: α={_a1}→{_a2}"
