"""Generated by data/generate_all.py
Parameters: L=100, DW=15, DT=0.25, sx=8.0, r_m=20, K1=1.0, K2=0.5
"""
import numpy as np

k_vals = np.array([0.300, 0.500, 0.700, 0.900, 1.100, 1.300, 1.500])

# sigma_tr(k) at various alpha, R=5, NNN gauging
sigma_nnn = {
    0.10: np.array([2.544, 2.064, 1.694, 1.397, 1.226, 1.130, 1.070]),
    0.15: np.array([7.140, 5.054, 4.006, 3.245, 2.834, 2.577, 2.429]),
    0.20: np.array([14.904, 9.624, 7.403, 5.909, 5.127, 4.603, 4.312]),
    0.25: np.array([25.423, 15.555, 11.711, 9.262, 7.981, 7.093, 6.603]),
    0.30: np.array([37.353, 22.189, 16.471, 12.979, 11.103, 9.804, 9.069]),
}

# ── Self-consistency ─────────────────────────────────────────────
# sigma_nnn grows with alpha at fixed k
for _ik in range(7):
    for _a1, _a2 in [(0.10, 0.15), (0.15, 0.20), (0.20, 0.25), (0.25, 0.30)]:
        assert sigma_nnn[_a2][_ik] > sigma_nnn[_a1][_ik], \
            f"sigma_nnn not monotonic in alpha at k index {_ik}: α={_a1}→{_a2}"
