"""Generated by data/generate_all.py
Parameters: L=100, DW=15, DT=0.25, sx=8.0, r_m=20, K1=1.0, K2=0.5
"""
import numpy as np

k_vals = np.array([0.300, 0.500, 0.700, 0.900, 1.100, 1.300, 1.500])

# Total per-bond sigma_tr
sigma_bond = np.array([0.0469, 0.0486, 0.0517, 0.0562, 0.0628, 0.0723, 0.0857])

# Polarization-resolved (alpha=0.30)
sigma_xx = np.array([0.0467, 0.0479, 0.0503, 0.0535, 0.0580, 0.0642, 0.0721])
sigma_xy = np.array([0.0002, 0.0007, 0.0015, 0.0028, 0.0048, 0.0081, 0.0136])

# ── Self-consistency ─────────────────────────────────────────────
# sigma_xx + sigma_xy ≈ sigma_bond (remainder is sigma_xz; rounding tolerance)
assert all(np.abs(sigma_xx + sigma_xy - sigma_bond) < 0.001), \
    "sigma_xx + sigma_xy ≠ sigma_bond beyond rounding"
assert len(sigma_bond) == len(k_vals) == 7
assert all(sigma_bond > 0), "sigma_bond must be positive"
assert np.mean(sigma_xx) > np.mean(sigma_xy), \
    "sigma_xx should dominate sigma_xy on average"
